// 📖 오프라인 표현집 — 신호 없이도(에어플레인 모드) 쓰는 선교 현장 필수 문장.
// ko/en/th/lo 는 앱에 내장(완전 오프라인). 그 외 언어는 런타임에 온라인 번역+캐시로 채운다.
// (i18n-specialist 가 km/vi/my/id/ms/tl 등을 추가·검증할 자리)

export type Phrase = { id: string; t: Record<string, string> };
export type PhraseCat = { id: string; icon: string; title: Record<string, string>; phrases: Phrase[] };

export const PHRASEBOOK: PhraseCat[] = [
  {
    id: "gospel", icon: "✝️",
    title: { ko: "복음 전하기", en: "Sharing the Gospel", th: "ประกาศข่าวประเสริฐ", lo: "ປະກາດຂ່າວປະເສີດ", km: "ការផ្សាយដំណឹងល្អ", vi: "Chia sẻ Tin Mừng", my: "သတင်းကောင်းဝေငှခြင်း", id: "Memberitakan Injil", ms: "Berkongsi Injil", tl: "Pagbabahagi ng Mabuting Balita" },
    phrases: [
      { id: "g1", t: { ko: "안녕하세요, 잠깐 이야기 나눌 수 있을까요?", en: "Hello, may I talk with you for a moment?", th: "สวัสดีครับ/ค่ะ ขอคุยด้วยสักครู่ได้ไหม", lo: "ສະບາຍດີ ຂໍລົມນຳແປບໜຶ່ງໄດ້ບໍ່?", km: "សួស្ដី តើខ្ញុំអាចនិយាយជាមួយលោកអ្នកមួយភ្លែតបានទេ?", vi: "Xin chào, tôi có thể nói chuyện với bạn một lát được không?", my: "မင်္ဂလာပါ၊ ခဏလောက် စကားပြောလို့ရမလား။", id: "Halo, bolehkah saya berbicara sebentar dengan Anda?", ms: "Helo, bolehkah saya berbual sebentar dengan anda?", tl: "Kumusta, maaari ba tayong mag-usap saglit?" } },
      { id: "g2", t: { ko: "하나님이 당신을 사랑하십니다.", en: "God loves you.", th: "พระเจ้าทรงรักคุณ", lo: "ພະເຈົ້າຮັກທ່ານ", km: "ព្រះជាម្ចាស់ស្រឡាញ់លោកអ្នក", vi: "Đức Chúa Trời yêu thương bạn.", my: "ဘုရားသခင်က သင့်ကို ချစ်တော်မူသည်။", id: "Allah mengasihi Anda.", ms: "Tuhan mengasihi anda.", tl: "Mahal ka ng Diyos." } },
      { id: "g3", t: { ko: "예수님은 당신을 위해 십자가에서 죽으셨습니다.", en: "Jesus died on the cross for you.", th: "พระเยซูสิ้นพระชนม์บนไม้กางเขนเพื่อคุณ", lo: "ພະເຍຊູໄດ້ສິ້ນຊີວິດເທິງໄມ້ກາງເຂນເພື່ອທ່ານ", km: "ព្រះយេស៊ូបានសោយទិវង្គតនៅលើឈើឆ្កាងសម្រាប់លោកអ្នក", vi: "Chúa Giê-su đã chết trên thập tự giá vì bạn.", my: "ယေရှုသည် သင့်အတွက် လက်ဝါးကပ်တိုင်ပေါ်တွင် အသေခံတော်မူခဲ့သည်။", id: "Yesus mati di kayu salib untuk Anda.", ms: "Yesus mati di kayu salib untuk anda.", tl: "Namatay si Hesus sa krus para sa iyo." } },
      { id: "g4", t: { ko: "예수님은 죽음에서 다시 살아나셨습니다.", en: "Jesus rose from the dead.", th: "พระเยซูทรงเป็นขึ้นจากความตาย", lo: "ພະເຍຊູໄດ້ເປັນຄືນຈາກຄວາມຕາຍ", km: "ព្រះយេស៊ូបានរស់ឡើងវិញពីការសុគត", vi: "Chúa Giê-su đã sống lại từ cõi chết.", my: "ယေရှုသည် သေခြင်းမှ ရှင်ပြန်ထမြောက်တော်မူခဲ့သည်။", id: "Yesus bangkit dari kematian.", ms: "Yesus bangkit daripada kematian.", tl: "Nabuhay muli si Hesus mula sa kamatayan." } },
      { id: "g5", t: { ko: "하나님은 당신을 위한 좋은 계획을 가지고 계십니다.", en: "God has a good plan for your life.", th: "พระเจ้าทรงมีแผนการที่ดีสำหรับชีวิตคุณ", lo: "ພະເຈົ້າມີແຜນການທີ່ດີສຳລັບຊີວິດຂອງທ່ານ", km: "ព្រះជាម្ចាស់មានគម្រោងដ៏ល្អសម្រាប់ជីវិតរបស់លោកអ្នក", vi: "Đức Chúa Trời có một kế hoạch tốt lành cho cuộc đời bạn.", my: "ဘုရားသခင်သည် သင့်ဘဝအတွက် ကောင်းသော အကြံအစည်တော် ရှိသည်။", id: "Allah memiliki rencana yang baik bagi hidup Anda.", ms: "Tuhan mempunyai rancangan yang baik untuk hidup anda.", tl: "May mabuting plano ang Diyos para sa iyong buhay." } },
      { id: "g6", t: { ko: "누구든지 예수님을 믿으면 영원한 생명을 얻습니다.", en: "Whoever believes in Jesus has eternal life.", th: "ทุกคนที่เชื่อในพระเยซูจะมีชีวิตนิรันดร์", lo: "ທຸກຄົນທີ່ເຊື່ອໃນພະເຍຊູຈະມີຊີວິດນິລັນດອນ", km: "អ្នកណាដែលជឿលើព្រះយេស៊ូ នឹងបានជីវិតអស់កល្បជានិច្ច", vi: "Ai tin nhận Chúa Giê-su thì được sự sống đời đời.", my: "ယေရှုကို ယုံကြည်သူတိုင်း ထာဝရအသက်ကို ရရှိမည်။", id: "Setiap orang yang percaya kepada Yesus memiliki hidup yang kekal.", ms: "Sesiapa yang percaya kepada Yesus akan beroleh hidup yang kekal.", tl: "Ang sinumang sumampalataya kay Hesus ay magkakaroon ng buhay na walang hanggan." } },
      { id: "g7", t: { ko: "함께 기도해 드려도 될까요?", en: "May I pray for you?", th: "ขออธิษฐานเผื่อคุณได้ไหม", lo: "ຂໍອະທິຖານເພື່ອທ່ານໄດ້ບໍ່?", km: "តើខ្ញុំអាចអធិស្ឋានឲ្យលោកអ្នកបានទេ?", vi: "Tôi có thể cầu nguyện cho bạn được không?", my: "သင့်အတွက် ဆုတောင်းပေးလို့ ရမလား။", id: "Bolehkah saya mendoakan Anda?", ms: "Bolehkah saya mendoakan anda?", tl: "Maaari ba kitang ipanalangin?" } },
      { id: "g8", t: { ko: "예수님을 마음에 영접하시겠어요?", en: "Would you like to receive Jesus into your heart?", th: "คุณอยากต้อนรับพระเยซูเข้ามาในใจไหม", lo: "ທ່ານຢາກຕ້ອນຮັບພະເຍຊູເຂົ້າມາໃນໃຈບໍ່?", km: "តើលោកអ្នកចង់ទទួលព្រះយេស៊ូចូលក្នុងចិត្តរបស់លោកអ្នកទេ?", vi: "Bạn có muốn tiếp nhận Chúa Giê-su vào lòng mình không?", my: "ယေရှုကို သင့်နှလုံးသားထဲသို့ လက်ခံချင်ပါသလား။", id: "Maukah Anda menerima Yesus di dalam hati Anda?", ms: "Adakah anda mahu menerima Yesus ke dalam hati anda?", tl: "Gusto mo bang tanggapin si Hesus sa iyong puso?" } },
      { id: "g9", t: { ko: "교회에 함께 가보시겠어요?", en: "Would you like to come to church with us?", th: "อยากไปโบสถ์กับเราไหม", lo: "ຢາກໄປໂບດກັບພວກເຮົາບໍ່?", km: "តើលោកអ្នកចង់ទៅព្រះវិហារជាមួយយើងទេ?", vi: "Bạn có muốn cùng chúng tôi đến nhà thờ không?", my: "ကျွန်တော်တို့နှင့်အတူ ဘုရားကျောင်းသို့ လာချင်ပါသလား။", id: "Maukah Anda pergi ke gereja bersama kami?", ms: "Adakah anda mahu ke gereja bersama kami?", tl: "Gusto mo bang sumama sa amin sa simbahan?" } },
      { id: "g10", t: { ko: "하나님께서 당신을 축복하시길 바랍니다.", en: "May God bless you.", th: "ขอพระเจ้าอวยพรคุณ", lo: "ຂໍພະເຈົ້າອວຍພອນທ່ານ", km: "សូមព្រះជាម្ចាស់ប្រទានពរដល់លោកអ្នក", vi: "Nguyện Đức Chúa Trời ban phước cho bạn.", my: "ဘုရားသခင် သင့်ကို ကောင်းချီးပေးပါစေ။", id: "Semoga Allah memberkati Anda.", ms: "Semoga Tuhan memberkati anda.", tl: "Nawa'y pagpalain ka ng Diyos." } },
    ],
  },
  {
    id: "daily", icon: "💬",
    title: { ko: "생활·여행 회화", en: "Daily & Travel", th: "ชีวิตประจำวันและท่องเที่ยว", lo: "ຊີວິດປະຈຳວັນ ແລະ ທ່ອງທ່ຽວ", km: "ជីវិតប្រចាំថ្ងៃ និងការធ្វើដំណើរ", vi: "Hằng ngày & Du lịch", my: "နေ့စဉ်နှင့် ခရီးသွား", id: "Sehari-hari & Perjalanan", ms: "Harian & Perjalanan", tl: "Pang-araw-araw at Paglalakbay" },
    phrases: [
      { id: "d1", t: { ko: "안녕하세요", en: "Hello", th: "สวัสดี", lo: "ສະບາຍດີ", km: "សួស្ដី", vi: "Xin chào", my: "မင်္ဂလာပါ", id: "Halo", ms: "Helo", tl: "Kumusta" } },
      { id: "d2", t: { ko: "감사합니다", en: "Thank you", th: "ขอบคุณ", lo: "ຂອບໃຈ", km: "អរគុណ", vi: "Cảm ơn", my: "ကျေးဇူးတင်ပါတယ်", id: "Terima kasih", ms: "Terima kasih", tl: "Salamat" } },
      { id: "d3", t: { ko: "죄송합니다 / 실례합니다", en: "Sorry / Excuse me", th: "ขอโทษ", lo: "ຂໍໂທດ", km: "សុំទោស", vi: "Xin lỗi", my: "တောင်းပန်ပါတယ်", id: "Maaf / Permisi", ms: "Maaf / Tumpang lalu", tl: "Pasensya na / Mawalang-galang" } },
      { id: "d4", t: { ko: "네 / 아니요", en: "Yes / No", th: "ใช่ / ไม่", lo: "ແມ່ນ / ບໍ່", km: "បាទ/ចាស / ទេ", vi: "Vâng / Không", my: "ဟုတ်ကဲ့ / မဟုတ်ဘူး", id: "Ya / Tidak", ms: "Ya / Tidak", tl: "Oo / Hindi" } },
      { id: "d5", t: { ko: "이것은 얼마예요?", en: "How much is this?", th: "อันนี้ราคาเท่าไหร่", lo: "ອັນນີ້ລາຄາເທົ່າໃດ?", km: "តើនេះថ្លៃប៉ុន្មាន?", vi: "Cái này giá bao nhiêu?", my: "ဒါ ဘယ်လောက်လဲ။", id: "Berapa harga ini?", ms: "Berapa harga ini?", tl: "Magkano ito?" } },
      { id: "d6", t: { ko: "화장실이 어디예요?", en: "Where is the toilet?", th: "ห้องน้ำอยู่ที่ไหน", lo: "ຫ້ອງນ້ຳຢູ່ໃສ?", km: "តើបន្ទប់ទឹកនៅឯណា?", vi: "Nhà vệ sinh ở đâu?", my: "အိမ်သာ ဘယ်မှာလဲ။", id: "Di mana toilet?", ms: "Di mana tandas?", tl: "Nasaan ang banyo?" } },
      { id: "d7", t: { ko: "도와주시겠어요?", en: "Can you help me?", th: "ช่วยฉันหน่อยได้ไหม", lo: "ຊ່ວຍຂ້ອຍແດ່ໄດ້ບໍ່?", km: "តើអ្នកអាចជួយខ្ញុំបានទេ?", vi: "Bạn có thể giúp tôi không?", my: "ကျွန်တော့်ကို ကူညီပေးနိုင်မလား။", id: "Bisakah Anda membantu saya?", ms: "Bolehkah anda membantu saya?", tl: "Maaari mo ba akong tulungan?" } },
      { id: "d8", t: { ko: "천천히 말해 주세요", en: "Please speak slowly", th: "พูดช้าๆ หน่อยได้ไหม", lo: "ກະລຸນາເວົ້າຊ້າໆ", km: "សូមនិយាយយឺតៗ", vi: "Xin nói chậm lại", my: "ဖြည်းဖြည်း ပြောပေးပါ", id: "Tolong bicara pelan-pelan", ms: "Tolong cakap perlahan-lahan", tl: "Mangyaring magsalita nang mabagal" } },
      { id: "d9", t: { ko: "이해하지 못했어요", en: "I don't understand", th: "ฉันไม่เข้าใจ", lo: "ຂ້ອຍບໍ່ເຂົ້າໃຈ", km: "ខ្ញុំមិនយល់ទេ", vi: "Tôi không hiểu", my: "ကျွန်တော် နားမလည်ဘူး", id: "Saya tidak mengerti", ms: "Saya tidak faham", tl: "Hindi ko maintindihan" } },
      { id: "d10", t: { ko: "길을 알려주시겠어요?", en: "Can you show me the way?", th: "ช่วยบอกทางหน่อยได้ไหม", lo: "ຊ່ວຍບອກທາງແດ່ໄດ້ບໍ່?", km: "តើអ្នកអាចប្រាប់ផ្លូវខ្ញុំបានទេ?", vi: "Bạn có thể chỉ đường cho tôi không?", my: "လမ်းညွှန်ပြပေးနိုင်မလား။", id: "Bisakah Anda menunjukkan jalannya?", ms: "Bolehkah anda tunjukkan jalan?", tl: "Maaari mo bang ituro sa akin ang daan?" } },
      { id: "d11", t: { ko: "이름이 뭐예요?", en: "What is your name?", th: "คุณชื่ออะไร", lo: "ທ່ານຊື່ຫຍັງ?", km: "តើអ្នកឈ្មោះអ្វី?", vi: "Bạn tên là gì?", my: "နာမည် ဘယ်လိုခေါ်လဲ။", id: "Siapa nama Anda?", ms: "Siapa nama anda?", tl: "Ano ang pangalan mo?" } },
      { id: "d12", t: { ko: "만나서 반갑습니다", en: "Nice to meet you", th: "ยินดีที่ได้รู้จัก", lo: "ຍິນດີທີ່ໄດ້ຮູ້ຈັກ", km: "រីករាយដែលបានជួបលោកអ្នក", vi: "Rất vui được gặp bạn", my: "တွေ့ရတာ ဝမ်းသာပါတယ်", id: "Senang bertemu dengan Anda", ms: "Gembira bertemu dengan anda", tl: "Ikinagagalak kitang makilala" } },
    ],
  },
  {
    id: "emergency", icon: "🚑",
    title: { ko: "긴급·의료", en: "Emergency & Medical", th: "ฉุกเฉินและการแพทย์", lo: "ສຸກເສີນ ແລະ ການແພດ", km: "សង្គ្រោះបន្ទាន់ និងវេជ្ជសាស្ត្រ", vi: "Khẩn cấp & Y tế", my: "အရေးပေါ်နှင့် ဆေးဘက်ဆိုင်ရာ", id: "Darurat & Medis", ms: "Kecemasan & Perubatan", tl: "Emergency at Medikal" },
    phrases: [
      { id: "e1", t: { ko: "도와주세요!", en: "Help!", th: "ช่วยด้วย!", lo: "ຊ່ວຍດ້ວຍ!", km: "ជួយផង!", vi: "Cứu với!", my: "ကူညီပါ!", id: "Tolong!", ms: "Tolong!", tl: "Saklolo!" } },
      { id: "e2", t: { ko: "응급상황이에요", en: "It's an emergency", th: "เป็นเหตุฉุกเฉิน", lo: "ເປັນເຫດສຸກເສີນ", km: "នេះជាករណីសង្គ្រោះបន្ទាន់", vi: "Đây là trường hợp khẩn cấp", my: "အရေးပေါ်အခြေအနေ ဖြစ်နေပါတယ်", id: "Ini keadaan darurat", ms: "Ini kecemasan", tl: "May emergency" } },
      { id: "e3", t: { ko: "의사가 필요해요", en: "I need a doctor", th: "ฉันต้องการหมอ", lo: "ຂ້ອຍຕ້ອງການໝໍ", km: "ខ្ញុំត្រូវការគ្រូពេទ្យ", vi: "Tôi cần bác sĩ", my: "ကျွန်တော် ဆရာဝန် လိုအပ်ပါတယ်", id: "Saya butuh dokter", ms: "Saya perlukan doktor", tl: "Kailangan ko ng doktor" } },
      { id: "e4", t: { ko: "병원이 어디예요?", en: "Where is the hospital?", th: "โรงพยาบาลอยู่ที่ไหน", lo: "ໂຮງໝໍຢູ່ໃສ?", km: "តើមន្ទីរពេទ្យនៅឯណា?", vi: "Bệnh viện ở đâu?", my: "ဆေးရုံ ဘယ်မှာလဲ။", id: "Di mana rumah sakit?", ms: "Di mana hospital?", tl: "Nasaan ang ospital?" } },
      { id: "e5", t: { ko: "약국이 어디예요?", en: "Where is the pharmacy?", th: "ร้านขายยาอยู่ที่ไหน", lo: "ຮ້ານຂາຍຢາຢູ່ໃສ?", km: "តើឱសថស្ថាននៅឯណា?", vi: "Hiệu thuốc ở đâu?", my: "ဆေးဆိုင် ဘယ်မှာလဲ။", id: "Di mana apotek?", ms: "Di mana farmasi?", tl: "Nasaan ang botika?" } },
      { id: "e6", t: { ko: "아파요", en: "It hurts / I am in pain", th: "ฉันเจ็บ/ปวด", lo: "ຂ້ອຍເຈັບ", km: "ខ្ញុំឈឺ", vi: "Tôi bị đau", my: "နာနေပါတယ်", id: "Saya kesakitan", ms: "Saya sakit", tl: "Masakit / May sakit ako" } },
      { id: "e7", t: { ko: "경찰을 불러주세요", en: "Please call the police", th: "กรุณาเรียกตำรวจ", lo: "ກະລຸນາເອີ້ນຕຳຫຼວດ", km: "សូមហៅប៉ូលីស", vi: "Xin gọi cảnh sát", my: "ကျေးဇူးပြု၍ ရဲ ခေါ်ပေးပါ", id: "Tolong panggil polisi", ms: "Tolong panggil polis", tl: "Pakitawag ang pulis" } },
      { id: "e8", t: { ko: "길을 잃었어요", en: "I am lost", th: "ฉันหลงทาง", lo: "ຂ້ອຍຫຼົງທາງ", km: "ខ្ញុំវង្វេងផ្លូវ", vi: "Tôi bị lạc đường", my: "လမ်းပျောက်နေပါတယ်", id: "Saya tersesat", ms: "Saya sesat", tl: "Naligaw ako" } },
      { id: "e9", t: { ko: "여권을 잃어버렸어요", en: "I lost my passport", th: "ฉันทำหนังสือเดินทางหาย", lo: "ຂ້ອຍເຮັດໜັງສືຜ່ານແດນເສຍ", km: "ខ្ញុំបាត់លិខិតឆ្លងដែន", vi: "Tôi bị mất hộ chiếu", my: "နိုင်ငံကူးလက်မှတ် ပျောက်သွားပါတယ်", id: "Saya kehilangan paspor", ms: "Saya kehilangan pasport", tl: "Nawala ang pasaporte ko" } },
      { id: "e10", t: { ko: "한국 대사관에 연락해 주세요", en: "Please contact the Korean embassy", th: "กรุณาติดต่อสถานทูตเกาหลี", lo: "ກະລຸນາຕິດຕໍ່ສະຖານທູດເກົາຫຼີ", km: "សូមទាក់ទងស្ថានទូតកូរ៉េ", vi: "Xin liên hệ với đại sứ quán Hàn Quốc", my: "ကိုရီးယားသံရုံးကို ဆက်သွယ်ပေးပါ", id: "Tolong hubungi Kedutaan Korea", ms: "Sila hubungi Kedutaan Korea", tl: "Pakikontak ang embahada ng Korea" } },
    ],
  },
];
